### ISSUE TITLE
Protobuf MenuItem does not contain offerName

### ISSUE THREAD

**Issue by ShirleyNekoDev** [HPI-de/hpi-cloud#67]
We require offerName in the protobuf objects:

### Example:

```
offerName: "Angebot 1"
counter: "1"
title: "Quarkkeulchen mit Vanillequark oder Apfelmus"
```

```
offerName: "Angebot 4"
counter: "Außengrill"
title: "Hamburger"
```

**Comment by JonasWanke** [comment]
@ShirleyNekoDev This is not an issue of this repository, but has to be changed in hpi-de/hpi-cloud-apis. Can you please file an issue there?

**Comment by ShirleyNekoDev** [comment]
Done with https://github.com/HPI-de/hpi-cloud-apis/pull/80 and 3be6644dd952499224728a942fb4703ed8237a51.
